image: node:8.11.1 # can be upgraded, depending on your node version used

stages:
  - build
  - deploy

cache:
  paths:
    - ./node_modules/

buildnode:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/  # This is what we want to publish
  only:
    refs:
      - testPubGitlab
  except:
    changes:
      - .gitlab-ci.yml

deploys3:
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - buildnode      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - pip install awscli # Install the SDK
  script:
    - case ${CI_COMMIT_REF_NAME} in
        testPubGitlab) S3_FOLDER_NAME="act-tripkit.tripgo.com" ;;
      esac
    - echo ${S3_FOLDER_NAME}
#    - aws s3 cp build s3://${S3_FOLDER_NAME} --recursive
    - aws s3 sync --delete build s3://${S3_FOLDER_NAME}
    - echo "Purge https://${S3_FOLDER_NAME}/embed.js"
    - 'curl -X POST "https://api.cloudflare.com/client/v4/zones/e4eb074c0d924353ba3da074e7fa5f87/purge_cache" -H "X-Auth-Email: support@skedgo.com" -H "X-Auth-Key: ${CF_X_AUTH_KEY}" -H "Content-Type: application/json" --data "{\"files\":[\"https://${S3_FOLDER_NAME}/embed.js\"]}"'
  only:
    refs:
      - testPubGitlab
  except:
    changes:
      - .gitlab-ci.yml