image: node:14.17.6 # can be upgraded, depending on your node version used

stages:
  - build
  - deploy

cache:
  paths:
    - ./node_modules/

buildnode:
  stage: build
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - dist/  # This is what we want to publish
  only:
    refs:
      - tripgoBeta
      - tripgoProd
  except:
    changes:
      - .gitlab-ci.yml

deploy_beta:
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - buildnode      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}
    - pip install awscli # Install the SDK
  script:
    - S3_FOLDER_NAME="tripkit.tripgo.com"
    - echo ${S3_FOLDER_NAME}
    - aws s3 sync --delete dist s3://${S3_FOLDER_NAME}
    - echo "Purge https://${S3_FOLDER_NAME}/*"
    - 'curl -X POST "https://api.cloudflare.com/client/v4/zones/e4eb074c0d924353ba3da074e7fa5f87/purge_cache" -H "X-Auth-Email: root@skedgo.com" -H "X-Auth-Key: ${CF_X_AUTH_KEY}" -H "Content-Type: application/json" --data "{\"files\":[\"https://${S3_FOLDER_NAME}/*\"]}"'
  environment:
      name: beta
      url: https://tripkit.tripgo.com
  only:
    refs:
      - tripgoBeta
  except:
    changes:
      - .gitlab-ci.yml

deploy_production:
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - buildnode      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}
    - pip install awscli # Install the SDK
  script:
    - S3_FOLDER_NAME="tripgo.com"
    - echo ${S3_FOLDER_NAME}
    - aws s3 sync --delete dist s3://${S3_FOLDER_NAME}
    - echo "Purge https://${S3_FOLDER_NAME}/*"
    - 'curl -X POST "https://api.cloudflare.com/client/v4/zones/e4eb074c0d924353ba3da074e7fa5f87/purge_cache" -H "X-Auth-Email: root@skedgo.com" -H "X-Auth-Key: ${CF_X_AUTH_KEY}" -H "Content-Type: application/json" --data "{\"files\":[\"https://${S3_FOLDER_NAME}/*\"]}"'
  environment:
        name: production
        url: https://tripgo.com
  only:
    refs:
      - tripgoProd
  except:
    changes:
      - .gitlab-ci.yml