site_name: TripKit SDK for React
site_author: SkedGo Pty Ltd
site_description: Documentation of TripKit React - the React SDK of the TripGo API.
docs_dir: src_mkdocs
copyright: © 2025 SkedGo. All rights reserved.

nav:
    - Getting Started: index.md
    - SDK Reference:
          - "Main SDK Component: TKRoot": reference/#/Main%20SDK%20component%3A%20TKRoot
          - Customization: reference/#/Customization
          - Example Use Cases: reference/#/Example%20Use%20Cases
          - Components API: reference/#/Components%20API

theme:
    name: skedgo
    highlightjs: true
    hljs_style: atom-one-dark

markdown_extensions:
    - toc:
          permalink: "#"
